services:
  - type: web
    name: surreal-chat
    env: python
    buildCommand: ""
    startCommand: uvicorn void_call:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
