services:
  - type: web
    name: surreal-chat
    env: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
